### ISSUE TITLE
`StateLossCallback.cls` Affected by GitHub EOL Conversion

### ISSUE THREAD

**Issue by WNKLER** [cristianbuse/VBA-StateLossCallback#5]
FYI, GitHub wrongly changed the EOL format of `StateLossCallback.cls` upon upload. 
It was changed from Windows (CR LF) to Unix (LF); replacing all [CR LF] with [LF]. 

This prevents the downloaded file from importing correctly into the VB/VBA IDE.

**Comment by cristianbuse** [comment]
Hi @Finatra ,

Thank you for the feedback! I am aware of the issue but was quite busy in the last few weeks and I am planning anyway to make changes to this repository. 

I've already added the fix to other repositories by [updating](https://github.com/cristianbuse/Excel-VBA-Tools/commit/0ffc42f5dc1806c1924ab7918f1c53e9d4cabb88) the ```.gitattributes``` file and then renormalizing the files.

Will update this one in the next few weeks.

**Comment by cristianbuse** [comment]
Fixed in 4252b7f71d055b79863a02ec78425513b7435bcb

Thanks!
